### ISSUE TITLE
multi-GPU training killed by `SIGSEGV`

### ISSUE THREAD

**Issue by shlee625** [universome/inr-gan#13]
This is another issue besides my last one.

When I run multi-GPU training, the processes are killed: `torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGSEGV` when evaluating metrics: `line 369` to `line 380` in `src/training/training_loop.py`. When I comment all these lines, the training goes fine without any error. Here is my brief system info.

```
OS: Ubuntu 20.04.2
GPUs: RTX 3090 X 2

python==3.8.10
cudatoolkit==11.1
torch==1.9.0
```
Here are the error messages.
```bash
Traceback (most recent call last):
  File "src/train.py", line 563, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/home/user/miniconda3/envs/inr-gan/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/miniconda3/envs/inr-gan/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/miniconda3/envs/inr-gan/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/miniconda3/envs/inr-gan/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/miniconda3/envs/inr-gan/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "src/train.py", line 558, in main
    torch.multiprocessing.spawn(fn=subprocess_fn, args=(args, temp_dir), nprocs=args.num_gpus)
  File "/home/user/miniconda3/envs/inr-gan/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/user/miniconda3/envs/inr-gan/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/user/miniconda3/envs/inr-gan/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 130, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGSEGV
```
I searched on Google to solve this problem but I can't find any clue for this problem. Do you have any idea about this problem? Thanks.

Best Wishes,
Lee

**Comment by universome** [comment]
Hi, Lee! The error is pretty strange, I do not remember having it. The first thing I would suspect is that your python/torch/cudatoolkit versions are higher than what we had in our case (see `environment.yaml`). This is also confirmed by this issue response: https://discuss.pytorch.org/t/how-to-fix-a-sigsegv-in-pytorch-when-using-distributed-training-e-g-ddp/113518/7

Have you tried creating the environment via conda? I.e. like this:
```
conda env create --file environment.yaml --prefix ./env
conda activate ./env
```

Also note that we didn't change the metrics code or that part of the training loop, so this error should also occur if you launch the official StyleGAN2-ADA repo: https://github.com/NVlabs/stylegan2-ada-pytorch. Could you try launching it?

**Comment by shlee625** [comment]
I only tried the training with cuda 11 because RTX 3090 only supports cuda >= 11.
It seems weird since other parts except metrics don't raise any error. I'll try to run the codes on other devices.
Thank you.

+)
The same error occurs when I launch the official StyleGAN2-ADA-Pytorch repo.

**Comment by universome** [comment]
@shlee625 

I tried to run the code on A6000 gpus with pytorch==1.9, torchvision=0.10.0 and cuda=11.4 and got the same error. After tracking down the issue, it turned out that the problem is in the "broken" InceptionV3 jit model, provided [here](https://github.com/universome/inr-gan/blob/master/src/metrics/frechet_inception_distance.py#L22). I suppose that to solve the issue, one needs to re-convert the InceptionV3 model into its jit version under the proper torch/torchvision versions. InceptionV3 is provided [here](https://github.com/mseitzer/pytorch-fid/blob/master/src/pytorch_fid/inception.py), but it might non-trivial to convert it to torchscript since this might require some refactoring

**Comment by universome** [comment]
Ok, I just tried to downgrade to pytorch1.7 and found that the issue persists. So, looks like the problem is in the incompatibility of the NVidia's InceptionV3 JIT model and Ampere GPUs.

**Comment by shlee625** [comment]
Thanks for the kind comments. As the architecture type of both RTX 3090 and A6000 is Ampere, this seems like the root cause of the error. I'll try on Quadro RTX 8000 of which architecture type is Turing and share the results.

**Edited**
Same error occurred while using Quadro RTX 8000.
