### ISSUE TITLE
Awesome idea!

### ISSUE THREAD

**Issue by akanimax** [universome/inr-gan#2]
Hello fellow Generative researchers!

This is not an issue :smile:. Just wanted to express my awe :stuck_out_tongue:...
Really cool idea, and thanks for the code! I'll explore your work in more details! 

Cheers :beers:!
@akanimax

p.s. This is not an issue :). Please close it at your disposal.

**Comment by universome** [comment]
Hi, Animesh! Thank you for your kind words :relaxed:

**Comment by danielkaifeng** [comment]
As a fans of CPPN network, I believe this would be a way to generate really high resolution and fantasy Image.

Especially for Anime image, the color and line sketch is simpler, use coordinator functions would greatly save the computational cost to generate image.

**Comment by universome** [comment]
I like the idea about Anime. Also, it might be easier to draw straight lines for coordinate-based models, since they have a direct feature input in the form of lines (i.e. 2d coordinates are getting encoded into 2d wavefronts)
