### ISSUE TITLE
There is no fast_inr_trainer module in current repository.

### ISSUE THREAD

**Issue by PeterouZh** [universome/inr-gan#5]
Great work! However, the current project is missing some files. Could you check your code to make sure it runs successfully, please? Thanks a lot.

![image](https://user-images.githubusercontent.com/26176709/104084344-0ac6ed80-5281-11eb-95d4-8a45b24ffca1.png)

**Comment by universome** [comment]
Hi! I am sorry for this and I am sorry such a late reply. I have fixed the imports now, thank you! Also, we have rewritten the whole codebase based on the rosinality/stylegan2-pytorch repo which improved the results for us. We are going to release it soon and the current repo will either become deprecated or will have a major update (we are not yet sure about how we'll release it). I am closing this issue, but if you have any other questions — feel free to reopen it.
