### ISSUE TITLE
Use of PatchConcatAndResize

### ISSUE THREAD

**Issue by ajabri** [universome/inr-gan#6]
Hi, thanks for sharing your awesome work!

I was just wondering about the `PatchConcatAndResize` transform in your code. Did you use this in any of the experiments reported in the paper? In particular, I'm curious if this kind of data augmentation was needed to get the extrapolation results to work well.

Thanks!
Allan

**Comment by universome** [comment]
Hi, Allan! No, `PatchConcatAndResize` was used only for a side experiment (we were trying to teach the model to perform better superresolution by using high-res patches for training) that didn't work and I forgot to delete all the unused code.

I will close the issue, but feel free to reopen it if you have any further questions.
